name 'robquistnl-puppet-kolab'
version '1.0.0'

author 'Rob Quist'
license 'GPL 2'
project_page 'http://www.github.com/RobQuistNL/puppet-kolab'
source 'https://github.com/RobQuistNL/puppet-kolab'
summary 'Puppet module for Kolab'
description 'This module installs and manages kolab mailserver. Check README for details.'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/firewall', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
